LOAD DATA
CHARACTERSET UTF8
INFILE 'kokyaku.csv'
INTO TABLE kokyaku
REPLACE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    KOKYAKU_ID SEQUENCE(MAX,1),
    NAME,
    JUSHO,
    CREATED_AT DATE "YYYYMMDD"
)